name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  IMAGE_NAME: "ghcr.io/golo300/c2-pixler"
  IMAGE_TAG: "unstable"

jobs:
  codeformat:
    name: Code format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26

      - name: Check code format
        run: nix flake check

  containerimage:
    name: Build and push container image
    runs-on: ubuntu-latest
    needs: [ codeformat ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26

      - name: Build container image
        run: nix build .#containerImage

      - name: Load containerimage into docker
        run: docker load < result

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container image to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

